language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=black
install:
    - pip install -r requirements/requirements-travis.txt
script:
    - tox
after_success:
    - coverage combine tests
    - coveralls
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
